config/routes.rb
SurvivalHub::Application.routes.draw do
  resources :users
  resources :posts

  get "users/create"
  get "users/show"
  get "users/new"
  get "users/all"
  get "users/signin"
  get "pages/home"
  get "pages/about"
  get "pages/contact"
  
  match '/home', :to => 'pages#home'
  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/signup', :to => 'users#new'
  match '/allusers', :to => 'users#all'

  root :to => 'pages#home'

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer         not null, primary key
#  context    :text
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#

class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#

require 'digest'

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation

  has_many :posts
  
  validates_presence_of :name
  validates_presence_of :email
  validates_uniqueness_of :email
  validates :password,  :presence => true,
                        :confirmation => true,
                        :length => { :within => 8..30 }
  
  before_save :encrypt_password
  
  #private
  
    def encrypt_password
      self.encrypted_password = Digest::SHA2.hexdigest(password)
    end
      
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def about
    @title = "About"
  end

  def contact
    @title = "Contact"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to @user
    else
      @title = "Sign up"
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end
  
  def new
    @title = "Sign up"
    @user = User.new
  end
  
  def all
    @title = "All users"
    @users = User.find(:all)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
# encoding: ISO8859-15
<!DOCTYPE html>
<html>
<head>
  <title>SurvivalHub | <%= @title %></title>
  <%= stylesheet_link_tag "blueprint/screen" %>
  <%= stylesheet_link_tag "application" %>
  <!--<%= javascript_include_tag "application" %>-->
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <header>
    <%= link_to image_tag("logo.png", :alt => "SurvivalHub", :class => "round"), home_path %>
    <nav class="round">
      <ul>
        <li><%= link_to "Home", home_path %></li>
        <li><%= link_to "Sign in", "#" %></li>
      </ul>
    </nav>
  </header>

  <section class="content round">

  <%= yield %>

  </section>

  <footer>
    <nav class="round">
      <ul>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
    </nav>
  </footer>
</div>
  
</body>
</html>

app/views/pages/about.html.erb
<h1>About this site</h1>
<p>You can use this site to keep track of your friends.</p>

app/views/pages/home.html.erb
<h1>Home</h1>
<p>Welcome to SurvivalHub. If you don't have an account, please <%= link_to "Sign up!", signup_path %></p>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h3>There were <%= pluralize(@user.errors.count, "error") %>:</h3>
    <ul>
    <% @user.errors.full_messages.each do |m| %>
      <li><%= m %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/all.html.erb
<h1>All users</h1>
<ul>
  <% @users.each do |u| %>
    <li><%= u.name %> &lt;<%= u.email %>&gt;</li>
  <% end %>
</ul>

    
  

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for(@user) do |u|%>

  <%= render 'shared/error_messages' %>

<div class="field">
<%= u.label :name %><br />
<%= u.text_field :name %><br />
</div>

<div class="field">
<%= u.label :email %><br />
<%= u.text_field :email %><br />
</div>

<div class="field">
<%= u.label :password %><br />
<%= u.password_field :password %><br />
</div>

<div class="field">
<%= u.label :password_confirmation %><br />
<%= u.password_field :password_confirmation %><br />
</div>

<br />
<%= u.submit "Sign up" %>

<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/signin.erb
<h1>Sign up</h1>
<%= form_tag :action => :create do %>

<%= label_tag :name, "Name: " %><br />
<%= text_field_tag :name %><br />

<%= label_tag :password, "Password: " %><br />
<%= password_field_tag :password %><br />

<%= submit_tag "Login" %>

<% end %>